### ISSUE TITLE
NVTOOLSEXT_INSTALL_PATH is invalid or inaccessible

### ISSUE THREAD

**Issue by andersy005** [numba/conda-recipe-cudatoolkit#10]
When building the windows package (https://ci.appveyor.com/project/andersy005/conda-recipes), I am getting `ValueError: NVTOOLSEXT_INSTALL_PATH is invalid or inaccessible.` 
The comments in [build.py](https://github.com/numba/conda-recipe-cudatoolkit/blob/master/scripts/build.py#L45) mention:

> "To accommodate nvtoolsext not being present as a DLL in the installer PE32s on windows, the windows variant of this script supports assembly directly from a pre-installed CUDA toolkit. The environment variable "NVTOOLSEXT_INSTALL_PATH" can be set to the
> installation path of the CUDA toolkit's NvToolsExt location (this is not the user defined install directory) and the DLL will be taken from that location."

 I can't figure out what to set this variable to. Is there a default value/known installation path for the `NVTOOLSEXT_INSTALL_PATH` variable?

**Comment by stuartarchibald** [comment]
It depends where and how you installed the CUDA toolkit on your local machine. It's typically something like:
```
C:\Program Files\NVIDIA Corporation\NVToolsExt\bin
```
if I recall correctly. 

If you can work out a way of getting it from the download source that'd be welcomed as this is essentially a work-around.

**Comment by andersy005** [comment]
Thanks, @stuartarchibald! I'll look into it.

**Comment by stuartarchibald** [comment]
No problem, if you manage to figure it out, a PR would be welcome :) Thanks.
